export const translations = {
    en: {
        resultIn: "Result in",
        amountPlaceholder: "Enter a numeric value",
        exchangeRateError: "Error getting exchange rate.",
        invalidCurrency: "Invalid selected currency.",
        invalidNumber: "Please enter a numeric value.",
        conversionError: "Error performing conversion",
        convertButton: "Convert",
        from_p: "From:",
        to_p: "To:",
        amount_p: "Amount",
        title: "Converter",
        USD: "USD - US Dollar",
        CNY: "CNY - Chinese Yuan",
        EUR: "EUR - Euro",
        BRL: "BRL - Brazilian Real",
    },
    pt_BR: {
        resultIn: "Resultado em",
        amountPlaceholder: "Insira um valor númerico",
        exchangeRateError: "Erro ao obter taxa de câmbio.",
        invalidCurrency: "Moeda selecionada inválida.",
        invalidNumber: "Por favor, digite um valor válido.",
        conversionError: "Erro ao obter conversâo.",
        convertButton: "Converter",
        from_p: "De:",
        to_p: "Para:",
        amount_p: "Quantia",
        title: "Conversor",
        USD: "USD - Dólar Americano",
        CNY: "CNY - Yuan Chinês",
        EUR: "EUR - Euro",
        BRL: "BRL - Real Brasileiro",
    }
}